name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # --- Checkout repo ---
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Setup Flutter SDK ---
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.35.6'

      # --- Cache pub dependencies ---
      - name: Cache Flutter packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # --- Install dependencies ---
      - name: Install dependencies
        run: flutter pub get

      # --- Build for GitHub Pages ---
      - name: Build Web for GitHub Pages
        run: flutter build web --release

      # --- Deploy to gh-pages branch ---
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build/web
          user_name: "Max Kovalev"
          user_email: "teasec4@users.noreply.github.com"